spring:
    application:
        name: turbine-amqp
    rabbitmq:
        host: 192.168.116.10
        port: 5672
        username: admin
        password: admin
server:
    port: 8989
management:
    port: 8990
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/ 