server:
    port: 5555
spring:
    application:
        name: api-gateway
        
        
zuul:
    routes:
        api-a-url:
            path: /api-a-url/**
            url: http://localhost:2222/        
# zuul:
#     routes:
#         api-a:
#             path: /api-a/**
#             serviceId: service-A
#         api-b:
#             path: /api-b/**
#             serviceId: service-B
            
eureka:
    client:
        serviceUrl:
            defaultZone:
                http://localhost:1111/eureka/
            


